# Generated by Django 4.2.1 on 2023-05-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_fk',
            new_name='user',
        ),
    ]
